import { pdfGenerator } from "./helper/pdfGenerator.js";

async function generatePdf() {
  let data = {
    items: [
      [
        {
          order_id: 1,
          invoice_fid: 1,
          combination_id: 1,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 28,
          price: 1999,
        },
        {
          order_id: 4,
          invoice_fid: 1,
          combination_id: 4,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 2,
          color_name: "TORTORA",
          color_pair: "MOCHA",
          qty: 22,
          price: 1999,
        },
        {
          order_id: 7,
          invoice_fid: 1,
          combination_id: 7,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 31,
          price: 1999,
        },
        {
          order_id: 10,
          invoice_fid: 1,
          combination_id: 10,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 4,
          color_name: "MARE",
          color_pair: "BLUE",
          qty: 33,
          price: 1999,
        },
        {
          order_id: 13,
          invoice_fid: 1,
          combination_id: 13,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 5,
          color_name: "ROSA",
          color_pair: "ROSE PINK",
          qty: 18,
          price: 1999,
        },
        {
          order_id: 16,
          invoice_fid: 1,
          combination_id: 16,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 6,
          color_name: "SALVIA",
          color_pair: "GREEN",
          qty: 14,
          price: 1999,
        },
      ],
      [
        {
          order_id: 2,
          invoice_fid: 1,
          combination_id: 2,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 45,
          price: 2999,
        },
        {
          order_id: 5,
          invoice_fid: 1,
          combination_id: 5,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 2,
          color_name: "TORTORA",
          color_pair: "MOCHA",
          qty: 19,
          price: 2999,
        },
        {
          order_id: 8,
          invoice_fid: 1,
          combination_id: 8,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 42,
          price: 2999,
        },
        {
          order_id: 11,
          invoice_fid: 1,
          combination_id: 11,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 4,
          color_name: "MARE",
          color_pair: "BLUE",
          qty: 44,
          price: 2999,
        },
        {
          order_id: 14,
          invoice_fid: 1,
          combination_id: 14,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 5,
          color_name: "ROSA",
          color_pair: "ROSE PINK",
          qty: 40,
          price: 2999,
        },
        {
          order_id: 17,
          invoice_fid: 1,
          combination_id: 17,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 6,
          color_name: "SALVIA",
          color_pair: "GREEN",
          qty: 36,
          price: 2999,
        },
      ],
      [
        {
          order_id: 3,
          invoice_fid: 1,
          combination_id: 3,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 38,
          price: 2999,
        },
        {
          order_id: 6,
          invoice_fid: 1,
          combination_id: 6,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 2,
          color_name: "TORTORA",
          color_pair: "MOCHA",
          qty: 47,
          price: 2999,
        },
        {
          order_id: 9,
          invoice_fid: 1,
          combination_id: 9,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 25,
          price: 2999,
        },
        {
          order_id: 12,
          invoice_fid: 1,
          combination_id: 12,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 4,
          color_name: "MARE",
          color_pair: "BLUE",
          qty: 29,
          price: 2999,
        },
        {
          order_id: 15,
          invoice_fid: 1,
          combination_id: 15,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 5,
          color_name: "ROSA",
          color_pair: "ROSE PINK",
          qty: 50,
          price: 2999,
        },
        {
          order_id: 18,
          invoice_fid: 1,
          combination_id: 18,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 6,
          color_name: "SALVIA",
          color_pair: "GREEN",
          qty: 26,
          price: 2999,
        },
      ],
      [
        {
          order_id: 19,
          invoice_fid: 1,
          combination_id: 19,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 7,
          color_name: "BEIGE",
          color_pair: "BEIGE",
          qty: 48,
          price: 1199,
        },
        {
          order_id: 21,
          invoice_fid: 1,
          combination_id: 21,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 23,
          price: 1199,
        },
        {
          order_id: 23,
          invoice_fid: 1,
          combination_id: 23,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 8,
          color_name: "AZZURRO",
          color_pair: "BLUE",
          qty: 15,
          price: 1199,
        },
        {
          order_id: 25,
          invoice_fid: 1,
          combination_id: 25,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 9,
          color_name: "VERDE",
          color_pair: "GREEN",
          qty: 30,
          price: 1199,
        },
      ],
      [
        {
          order_id: 20,
          invoice_fid: 1,
          combination_id: 20,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 7,
          color_name: "BEIGE",
          color_pair: "BEIGE",
          qty: 32,
          price: 1799,
        },
        {
          order_id: 22,
          invoice_fid: 1,
          combination_id: 22,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 37,
          price: 1799,
        },
        {
          order_id: 24,
          invoice_fid: 1,
          combination_id: 24,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 8,
          color_name: "AZZURRO",
          color_pair: "BLUE",
          qty: 49,
          price: 1799,
        },
        {
          order_id: 26,
          invoice_fid: 1,
          combination_id: 26,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 9,
          color_name: "VERDE",
          color_pair: "GREEN",
          qty: 11,
          price: 1799,
        },
        {
          order_id: 28,
          invoice_fid: 1,
          combination_id: 28,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 10,
          color_name: "ROSA",
          color_pair: "ROSE",
          qty: 21,
          price: 1799,
        },
      ],
      [
        {
          order_id: 29,
          invoice_fid: 1,
          combination_id: 29,
          product_name: "NUMBER THREE",
          product_id: 3,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 12,
          price: 1999,
        },
      ],
      [
        {
          order_id: 30,
          invoice_fid: 1,
          combination_id: 30,
          product_name: "NUMBER THREE",
          product_id: 3,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 20,
          price: 2999,
        },
      ],
      [
        {
          order_id: 1,
          invoice_fid: 1,
          combination_id: 1,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 28,
          price: 1999,
        },
        {
          order_id: 4,
          invoice_fid: 1,
          combination_id: 4,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 2,
          color_name: "TORTORA",
          color_pair: "MOCHA",
          qty: 22,
          price: 1999,
        },
        {
          order_id: 7,
          invoice_fid: 1,
          combination_id: 7,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 31,
          price: 1999,
        },
        {
          order_id: 10,
          invoice_fid: 1,
          combination_id: 10,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 4,
          color_name: "MARE",
          color_pair: "BLUE",
          qty: 33,
          price: 1999,
        },
        {
          order_id: 13,
          invoice_fid: 1,
          combination_id: 13,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 5,
          color_name: "ROSA",
          color_pair: "ROSE PINK",
          qty: 18,
          price: 1999,
        },
        {
          order_id: 16,
          invoice_fid: 1,
          combination_id: 16,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 6,
          color_name: "SALVIA",
          color_pair: "GREEN",
          qty: 14,
          price: 1999,
        },
      ],
      [
        {
          order_id: 2,
          invoice_fid: 1,
          combination_id: 2,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 45,
          price: 2999,
        },
        {
          order_id: 5,
          invoice_fid: 1,
          combination_id: 5,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 2,
          color_name: "TORTORA",
          color_pair: "MOCHA",
          qty: 19,
          price: 2999,
        },
        {
          order_id: 8,
          invoice_fid: 1,
          combination_id: 8,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 42,
          price: 2999,
        },
        {
          order_id: 11,
          invoice_fid: 1,
          combination_id: 11,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 4,
          color_name: "MARE",
          color_pair: "BLUE",
          qty: 44,
          price: 2999,
        },
        {
          order_id: 14,
          invoice_fid: 1,
          combination_id: 14,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 5,
          color_name: "ROSA",
          color_pair: "ROSE PINK",
          qty: 40,
          price: 2999,
        },
        {
          order_id: 17,
          invoice_fid: 1,
          combination_id: 17,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 6,
          color_name: "SALVIA",
          color_pair: "GREEN",
          qty: 36,
          price: 2999,
        },
      ],
      [
        {
          order_id: 3,
          invoice_fid: 1,
          combination_id: 3,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 38,
          price: 2999,
        },
        {
          order_id: 6,
          invoice_fid: 1,
          combination_id: 6,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 2,
          color_name: "TORTORA",
          color_pair: "MOCHA",
          qty: 47,
          price: 2999,
        },
        {
          order_id: 9,
          invoice_fid: 1,
          combination_id: 9,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 25,
          price: 2999,
        },
        {
          order_id: 12,
          invoice_fid: 1,
          combination_id: 12,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 4,
          color_name: "MARE",
          color_pair: "BLUE",
          qty: 29,
          price: 2999,
        },
        {
          order_id: 15,
          invoice_fid: 1,
          combination_id: 15,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 5,
          color_name: "ROSA",
          color_pair: "ROSE PINK",
          qty: 50,
          price: 2999,
        },
        {
          order_id: 18,
          invoice_fid: 1,
          combination_id: 18,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 6,
          color_name: "SALVIA",
          color_pair: "GREEN",
          qty: 26,
          price: 2999,
        },
      ],
      [
        {
          order_id: 19,
          invoice_fid: 1,
          combination_id: 19,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 7,
          color_name: "BEIGE",
          color_pair: "BEIGE",
          qty: 48,
          price: 1199,
        },
        {
          order_id: 21,
          invoice_fid: 1,
          combination_id: 21,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 23,
          price: 1199,
        },
        {
          order_id: 23,
          invoice_fid: 1,
          combination_id: 23,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 8,
          color_name: "AZZURRO",
          color_pair: "BLUE",
          qty: 15,
          price: 1199,
        },
        {
          order_id: 25,
          invoice_fid: 1,
          combination_id: 25,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 9,
          color_name: "VERDE",
          color_pair: "GREEN",
          qty: 30,
          price: 1199,
        },
        {
          order_id: 27,
          invoice_fid: 1,
          combination_id: 27,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 10,
          color_name: "ROSA",
          color_pair: "ROSE",
          qty: 46,
          price: 1199,
        },
      ],
      [
        {
          order_id: 20,
          invoice_fid: 1,
          combination_id: 20,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 7,
          color_name: "BEIGE",
          color_pair: "BEIGE",
          qty: 32,
          price: 1799,
        },
        {
          order_id: 22,
          invoice_fid: 1,
          combination_id: 22,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 37,
          price: 1799,
        },
        {
          order_id: 24,
          invoice_fid: 1,
          combination_id: 24,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 8,
          color_name: "AZZURRO",
          color_pair: "BLUE",
          qty: 49,
          price: 1799,
        },
        {
          order_id: 26,
          invoice_fid: 1,
          combination_id: 26,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 9,
          color_name: "VERDE",
          color_pair: "GREEN",
          qty: 11,
          price: 1799,
        },
        {
          order_id: 28,
          invoice_fid: 1,
          combination_id: 28,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 10,
          color_name: "ROSA",
          color_pair: "ROSE",
          qty: 21,
          price: 1799,
        },
      ],
      [
        {
          order_id: 29,
          invoice_fid: 1,
          combination_id: 29,
          product_name: "NUMBER THREE",
          product_id: 3,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 12,
          price: 1999,
        },
      ],
      [
        {
          order_id: 30,
          invoice_fid: 1,
          combination_id: 30,
          product_name: "NUMBER THREE",
          product_id: 3,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 20,
          price: 2999,
        },
      ],
      [
        {
          order_id: 1,
          invoice_fid: 1,
          combination_id: 1,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 28,
          price: 1999,
        },
        {
          order_id: 4,
          invoice_fid: 1,
          combination_id: 4,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 2,
          color_name: "TORTORA",
          color_pair: "MOCHA",
          qty: 22,
          price: 1999,
        },
        {
          order_id: 7,
          invoice_fid: 1,
          combination_id: 7,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 31,
          price: 1999,
        },
        {
          order_id: 10,
          invoice_fid: 1,
          combination_id: 10,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 4,
          color_name: "MARE",
          color_pair: "BLUE",
          qty: 33,
          price: 1999,
        },
        {
          order_id: 13,
          invoice_fid: 1,
          combination_id: 13,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 5,
          color_name: "ROSA",
          color_pair: "ROSE PINK",
          qty: 18,
          price: 1999,
        },
        {
          order_id: 16,
          invoice_fid: 1,
          combination_id: 16,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 6,
          color_name: "SALVIA",
          color_pair: "GREEN",
          qty: 14,
          price: 1999,
        },
      ],
      [
        {
          order_id: 2,
          invoice_fid: 1,
          combination_id: 2,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 45,
          price: 2999,
        },
        {
          order_id: 5,
          invoice_fid: 1,
          combination_id: 5,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 2,
          color_name: "TORTORA",
          color_pair: "MOCHA",
          qty: 19,
          price: 2999,
        },
        {
          order_id: 8,
          invoice_fid: 1,
          combination_id: 8,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 42,
          price: 2999,
        },
        {
          order_id: 11,
          invoice_fid: 1,
          combination_id: 11,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 4,
          color_name: "MARE",
          color_pair: "BLUE",
          qty: 44,
          price: 2999,
        },
        {
          order_id: 14,
          invoice_fid: 1,
          combination_id: 14,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 5,
          color_name: "ROSA",
          color_pair: "ROSE PINK",
          qty: 40,
          price: 2999,
        },
        {
          order_id: 17,
          invoice_fid: 1,
          combination_id: 17,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 6,
          color_name: "SALVIA",
          color_pair: "GREEN",
          qty: 36,
          price: 2999,
        },
      ],
      [
        {
          order_id: 3,
          invoice_fid: 1,
          combination_id: 3,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 38,
          price: 2999,
        },
        {
          order_id: 6,
          invoice_fid: 1,
          combination_id: 6,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 2,
          color_name: "TORTORA",
          color_pair: "MOCHA",
          qty: 47,
          price: 2999,
        },
        {
          order_id: 9,
          invoice_fid: 1,
          combination_id: 9,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 25,
          price: 2999,
        },
        {
          order_id: 12,
          invoice_fid: 1,
          combination_id: 12,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 4,
          color_name: "MARE",
          color_pair: "BLUE",
          qty: 29,
          price: 2999,
        },
        {
          order_id: 15,
          invoice_fid: 1,
          combination_id: 15,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 5,
          color_name: "ROSA",
          color_pair: "ROSE PINK",
          qty: 50,
          price: 2999,
        },
        {
          order_id: 18,
          invoice_fid: 1,
          combination_id: 18,
          product_name: "NUMBER ONE",
          product_id: 1,
          size_id: 3,
          size_value: "75 X 75",
          color_id: 6,
          color_name: "SALVIA",
          color_pair: "GREEN",
          qty: 26,
          price: 2999,
        },
      ],
      [
        {
          order_id: 19,
          invoice_fid: 1,
          combination_id: 19,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 7,
          color_name: "BEIGE",
          color_pair: "BEIGE",
          qty: 48,
          price: 1199,
        },
        {
          order_id: 21,
          invoice_fid: 1,
          combination_id: 21,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 23,
          price: 1199,
        },
        {
          order_id: 23,
          invoice_fid: 1,
          combination_id: 23,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 8,
          color_name: "AZZURRO",
          color_pair: "BLUE",
          qty: 15,
          price: 1199,
        },
        {
          order_id: 25,
          invoice_fid: 1,
          combination_id: 25,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 9,
          color_name: "VERDE",
          color_pair: "GREEN",
          qty: 30,
          price: 1199,
        },
        {
          order_id: 27,
          invoice_fid: 1,
          combination_id: 27,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 4,
          size_value: "40 X 60",
          color_id: 10,
          color_name: "ROSA",
          color_pair: "ROSE",
          qty: 46,
          price: 1199,
        },
      ],
      [
        {
          order_id: 20,
          invoice_fid: 1,
          combination_id: 20,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 7,
          color_name: "BEIGE",
          color_pair: "BEIGE",
          qty: 32,
          price: 1799,
        },
        {
          order_id: 22,
          invoice_fid: 1,
          combination_id: 22,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 3,
          color_name: "GRIGIO",
          color_pair: "GREY",
          qty: 37,
          price: 1799,
        },
        {
          order_id: 24,
          invoice_fid: 1,
          combination_id: 24,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 8,
          color_name: "AZZURRO",
          color_pair: "BLUE",
          qty: 49,
          price: 1799,
        },
        {
          order_id: 26,
          invoice_fid: 1,
          combination_id: 26,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 9,
          color_name: "VERDE",
          color_pair: "GREEN",
          qty: 11,
          price: 1799,
        },
        {
          order_id: 28,
          invoice_fid: 1,
          combination_id: 28,
          product_name: "BICOLOR",
          product_id: 2,
          size_id: 5,
          size_value: "50 X 80",
          color_id: 10,
          color_name: "ROSA",
          color_pair: "ROSE",
          qty: 21,
          price: 1799,
        },
      ],
      [
        {
          order_id: 29,
          invoice_fid: 1,
          combination_id: 29,
          product_name: "NUMBER THREE",
          product_id: 3,
          size_id: 1,
          size_value: " 50 X 80",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 12,
          price: 1999,
        },
      ],
      [
        {
          order_id: 30,
          invoice_fid: 1,
          combination_id: 30,
          product_name: "NUMBER THREE",
          product_id: 3,
          size_id: 2,
          size_value: " 55 X 110",
          color_id: 1,
          color_name: "CANAPA",
          color_pair: "BEIGE",
          qty: 20,
          price: 2999,
        },
      ],
    ],
  };

  try {
    // data.items = groupItemsBySizeAndColor(data.items);
    const fileName = "invoice_141_24_25";
    let buffer = await pdfGenerator(fileName, data);
  } catch (error) {
    console.error("Error in generatePdf:", error); // Log the error for debugging
  }
}
generatePdf();
